import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen justify-center items-center">
        <div className="h-screen w-screen md:max-w-[300px] md:max-h-[667px] md:rounded-xl overflow-hidden bg-primary">
          {children}
        </div>
      </body>
    </html>
  )
}
